'use strict';

// events that can be sent by client
exports.client = {
  auth: 'auth',
  disconnect: 'disconnect'
};

// events that are generated by server API
exports.server = {
  channelCreated: 'channel-created',
  userJoined: 'user-joined',
  userUnselectedChannel: 'user-unselected-channel',
  userSelectedChannel: 'user-selected-channel',
  changedDevice: 'changed-device',
  mediaStateUpdated: 'media-state-updated'
};

// events that are generated by socket module
exports.socket = {
  authSuccess: 'auth-success',
  channelCreated: 'channel-created',
  userJoined: 'user-joined',
  userUnselectedChannel: 'user-unselected-channel',
  userSelectedChannel: 'user-selected-channel',
  changedDevice: 'changed-device',
  mediaStateUpdated: 'media-state-updated'
};
