'use strict';

// room names
exports.rooms = {
  workspaceRoom: (id) => `workspace-room-${id}`,
  channelRoom: (id) => `channel-room-${id}`,
  userRoom: (id) => `user-room-${id}`
};

// events that can be sent by client
exports.client = {
  auth: 'auth',
  disconnect: 'disconnect'
};

// events that are generated by server API
exports.server = {
  channelCreated: 'channel-created',
  userJoined: 'user-joined',
  userUnselectedChannel: 'user-unselected-channel',
  userSelectedChannel: 'user-selected-channel',
  changedDevice: 'changed-device',
  mediaStateUpdated: 'media-state-updated',
  userLeavedWorkspace: 'user-leaved-workspace',
  channelDeleted: 'channel-deleted',
  userUpdated: 'user-updated',
  changeUserOnlineStatus: 'change-user-online-status'
};

// events that are generated by socket module
exports.socket = {
  authSuccess: 'auth-success',
  channelCreated: 'channel-created',
  userJoined: 'user-joined',
  userUnselectedChannel: 'user-unselected-channel',
  userSelectedChannel: 'user-selected-channel',
  changedDevice: 'user-changed-device',
  mediaStateUpdated: 'media-state-updated',
  userLeavedWorkspace: 'user-leaved-workspace',
  channelDeleted: 'channel-deleted',
  userUpdated: 'user-updated',
  onlineStatusChanged: 'online-status-updated',
  message: 'message',
  messageResponse: 'message-response'
};
