'use strict';

// events that can be sent by client
exports.client = {
  auth: 'auth',
  disconnect: 'disconnect'
};

// events that are generated by server API
exports.server = {
  channelCreated: 'channel-created',
  userJoined: 'user-joined',
  userSwitchesChannel: 'user-switches-channel'
};

// events that are generated by socket module
exports.socket = {
  authSuccess: 'auth-success',
  channelCreated: 'channel-created',
  userJoined: 'user-joined'
};
