---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  dotenv: |
    COOKIE_PASSWORD=you_have_to_set_very_long_string_and_it_should_be_protected_as_a_zenitsa_oka

    # Token lifespan
    ACCESS_TOKEN_LIFESPAN = {{ pluck .Values.global.env .Values.backend.access_token_lifespan | first | default .Values.backend.access_token_lifespan._default | toString }}
    REFRESH_TOKEN_LIFESPAN = {{ pluck .Values.global.env .Values.backend.refresh_token_lifespan | first | default .Values.backend.refresh_token_lifespan._default | toString }}
    EMAIL_VERIFICATION_CODE_LIFESPAN = {{ pluck .Values.global.env .Values.backend.email_verification_code_lifespan | first | default .Values.backend.email_verification_code_lifespan._default |  toString }}
    AUTH_LINK_LIFESPAN = {{ pluck .Values.global.env .Values.backend.auth_link_lifespan | first | default .Values.backend.auth_link_lifespan._default | toString }}

    # External authenticator credentials

    GOOGLE_CLIENT_ID={{ pluck .Values.global.env .Values.backend.google.id | first | default .Values.backend.google.id._default | quote }}
    GOOGLE_CLIENT_SECRET={{ pluck .Values.global.env .Values.backend.google.secret | first | default .Values.backend.google.secret._default | quote }}

    SLACK_CLIENT_ID={{ pluck .Values.global.env .Values.backend.slack.id | first | default .Values.backend.slack.id._default | quote }}
    SLACK_CLIENT_SECRET={{ pluck .Values.global.env .Values.backend.slack.secret | first | default .Values.backend.slack.secret._default | quote }}
    SLACK_VERIFICATION_TOKEN={{ pluck .Values.global.env .Values.backend.slack.verification_token | first | default .Values.backend.slack.verification_token._default | quote }}

    FACEBOOK_CLIENT_ID={{ pluck .Values.global.env .Values.backend.facebook.id | first | default .Values.backend.facebook.id._default | quote }}
    FACEBOOK_CLIENT_SECRET={{ pluck .Values.global.env .Values.backend.facebook.secret | first | default .Values.backend.facebook.secret._default | quote }}

    # @mailgun parameters
    MAILGUN_DOMAIN={{ pluck .Values.global.env .Values.backend.mailgun.domain | first | default .Values.backend.mailgun.domain._default | quote }}
    MAILGUN_APIKEY={{ pluck .Values.global.env .Values.backend.mailgun.apikey | first | default .Values.backend.mailgun.apikey._default | quote }}