---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ pluck .Values.global.env .Values.backend.replicas | first | default .Values.backend.replicas._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/app-config: {{ include (print $.Template.BasePath "/back-config.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa
      imagePullSecrets:
        - name: registrysecret
      initContainers:
        - name: migrate
{{ tuple "backend" . | include "werf_container_image" | indent 10 }}
          command: ["/bin/sh"]
          args:
            - -c
            - "yarn run migrate up"
          workingDir: /app/
          env:
{{ tuple "backend" . | include "werf_container_env" | indent 12 }}
{{- include "backend_env" . | indent 12 }}
      containers:
        - name: backend
{{ tuple "backend" . | include "werf_container_image" | indent 10 }}
          command: ["/bin/sh"]
          args:
            - -c
            - "yarn run dev"
          workingDir: /app/
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 512Mi
          env:
{{ tuple "backend" . | include "werf_container_env" | indent 12 }}
{{- include "backend_env" . | indent 12 }}
          ports:
            - containerPort: {{ .Values.backend.port }}
              name: web
          volumeMounts:
            - name: app-config
              mountPath: /app/.env
              subPath: dotenv
      volumes:
        - name: app-config
          configMap:
            name: {{ .Chart.Name }}-config


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
    - targetPort: web
      port: 80
      name: web
  selector:
    app: {{ .Chart.Name }}
