---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ pluck .Values.werf.env .Values.app.replicas | first | default .Values.app.replicas._default }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-config.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: {{ .Chart.Name }}
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/node
                operator: In
                values:
                - ""
      serviceAccountName: {{ .Chart.Name }}-sa
      imagePullSecrets:
        - name: registrysecret
      initContainers:
        - name: migrate
          image:  {{ .Values.werf.image.backend }}
          command: ["/bin/sh"]
          args:
            - -c
            - "yarn run migrate up -- --no-check-order"
          workingDir: /app/
          env:
{{- include "backend_env" . | indent 12 }}
      containers:
        - name: backend
          image:  {{ .Values.werf.image.backend }}
          command: ["/bin/sh"]
          args:
            - -c
            - "yarn run dev:node"
          workingDir: /app/
          resources:
            requests:
              memory: {{ pluck .Values.werf.env .Values.app.requests.memory | first | default .Values.app.requests.memory._default | quote }}
              cpu: {{ pluck .Values.werf.env .Values.app.requests.cpu | first | default .Values.app.requests.cpu._default | quote }}
            limits:
              memory: {{ pluck .Values.werf.env .Values.app.limits.memory | first | default .Values.app.limits.memory._default | quote }}
          env:
{{- include "backend_env" . | indent 12 }}
          ports:
            - containerPort: {{ .Values.app.port }}
              name: web
          readinessProbe:
            httpGet:
              path: /status
              port: web
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /status
              port: web
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 3
          volumeMounts:
            - name: app-config
              mountPath: /app/.env
              subPath: dotenv
      volumes:
        - name: app-config
          configMap:
            name: {{ .Chart.Name }}-config
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - targetPort: web
    port: 80
    name: web
  selector:
    app: {{ .Chart.Name }}
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Chart.Name }}
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: {{ .Chart.Name }}
  updatePolicy:
    updateMode: "Off"