---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ pluck .Values.global.env .Values.backend.url | first | default (printf "back-%s.%s" .Values.global.env .Values.backend.domain_base) }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: web
  tls:
  - hosts:
      - {{ pluck .Values.global.env .Values.backend.url | first | default (printf "back-%s.%s" .Values.global.env .Values.backend.domain_base) }}
    secretName: {{ printf "tls-%s" .Chart.Name | quote }}
