---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: janus-default
  labels:
    app: janus-default
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/janus-config.yaml") . | sha256sum }}
spec:
  replicas: {{ pluck .Values.global.env .Values.janus.replicas | first | default .Values.janus.replicas._default }}
  selector:
    matchLabels:
      app: janus-default
  template:
    metadata:
      labels:
        app: janus-default
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/janus-config.yaml") . | sha256sum }}
    spec:
      imagePullSecrets:
        - name: registrysecret
      containers:
        - name: gateway
{{ tuple "janus" . | include "werf_container_image" | indent 10 }}
          command: ["/opt/janus/bin/janus", "--nat-1-1=$(MY_POD_IP)"]
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          env:
{{ tuple "janus" . | include "werf_container_env" | indent 12 }}
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          ports:
            - containerPort: {{ pluck .Values.global.env .Values.janus.admin_port | first | default .Values.janus.admin_port._default }}
              name: admin
            - containerPort: 8088
              name: web
            - containerPort: 8188
              name: websocket
          volumeMounts:
            - name: configmap
              mountPath: /opt/janus/etc/janus
      volumes:
        - name: configmap
          configMap:
            name: janus-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: janus-default
  name: {{ pluck .Values.global.env .Values.janus.host | first | default .Values.janus.host._default }}
spec:
  ports:
    - targetPort: admin
      name: admin
      port: {{ pluck .Values.global.env .Values.janus.admin_port | first | default .Values.janus.admin_port._default }}
    - targetPort: web
      name: web
      port: 8088
    - targetPort: websocket
      port: 8188
      name: websocket
  selector:
    app: janus-default
