---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ printf "janus-%s" .Chart.Name | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ pluck .Values.global.env .Values.janus.public_url | first | default (printf "janus-%s.%s" .Values.global.env .Values.app.domain_base) }}
    http:
      paths:
      - path: /
        backend:
          serviceName: janus-default
          servicePort: web
  tls:
  - hosts:
      - {{ pluck .Values.global.env .Values.janus.public_url | first | default (printf "janus-%s.%s" .Values.global.env .Values.app.domain_base) }}
    secretName: {{ printf "janus-tls-%s" .Chart.Name | quote }}
