---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Chart.Name }}-sa
  namespace: {{ printf "heyka-%s" .Values.werf.env  }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ .Chart.Name }}-role
rules:
- apiGroups:
  - ""
  resources:
  - "nodes"
  verbs:
  - "get"
  - "list"

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Chart.Name }}-binding:{{.Values.werf.env }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Chart.Name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}-sa
  namespace: {{ printf "heyka-%s" .Values.werf.env }}
