redis:
  host:
    _default: redis-sentinel-proxy
  port:
    _default: 6379

postgres:
  host:
    _default: postgres
  port:
    _default: 6432

janus:
  host:
    _default: janus
  replicas:
    _default: 1

backend:
  url: {}
  port: 5000
  access_token_lifespan:
    _default: "3600000"
  refresh_token_lifespan:
    _default: "2678400000"
  email_verification_code_lifespan:
    _default: "3600000"
  auth_link_lifespan:
    _default: "600000"
  domain_base: dev.k8s.heyka.io
  replicas:
    _default: 1