redis:
  host:
    _default: redis-sentinel-proxy
  port:
    _default: 6379

postgres:
  host:
    _default: postgres
  port:
    _default: 6432

janus:
  kubernetes:
    enabled:
      dev: true
      stage: true
    host:
      _default: kubernetes.default
    janus_node_label:
      _default: "node-role.kubernetes.io/janus="
  external:
    enabled:
      dev: false
      stage: false
    url:
      _default: https://janus-test.heyka.io
    public_url:
      _default: https://janus-test.heyka.io

app:
  domain_main:
    _default: api.heyka.app
  domain_base: dev.k8s.heyka.io
  url: {}
  port: 5000
  access_token_lifespan:
    _default: "3600000"
  refresh_token_lifespan:
    _default: "2678400000"
  email_verification_code_lifespan:
    _default: "3600000"
  auth_link_lifespan:
    _default: "2592000000"
  watcher:
    replicas:
      _default: "0"
      stage: "1"
  replicas:
    _default: "1"
  requests:
    cpu:
      _default: "250m"
      stage: "500m"
      production: "1"
    memory:
      _default: "512Mi"
      stage: "1Gi"
      production: "2Gi"
  limits:
    memory:
      _default: "1Gi"
      stage: "2Gi"
      production: "4Gi"
